alias: "BATT: control"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.p_batt_forecast
  - platform: state
    entity_id:
      - sensor.p_grid_forecast
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.optim_status
        state: Optimal
        enabled: true
      - condition: numeric_state
        entity_id: sensor.inverter_battery_1_soc
        below: 13
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            below: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            below: -1
          - condition: numeric_state
            entity_id: sensor.unit_prod_price
            above: 0
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            data:
              value: "13"
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_power
                - number.inverter_prog2_power
                - number.inverter_prog3_power
                - number.inverter_prog4_power
                - number.inverter_prog5_power
                - number.inverter_prog6_power
            data:
              value: "{{states('sensor.p_batt_forecast')|float(0)|abs}}"
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: >-
                {{
                ([(states('sensor.p_batt_forecast')|float(0)|abs/410)|round(0,'ceil'),37]|sort)[0]
                }}
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: PV sell
            target:
              entity_id: input_text.batt_mode
        alias: PV sell
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            below: -1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            below: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            above: -1
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
            data:
              value: "100"
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: 37
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: PV charge
            target:
              entity_id: input_text.batt_mode
        alias: PV charge
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            below: -1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            above: 1
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: Allow Grid
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
            data:
              value: "100"
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: >-
                {{
                ([(states('sensor.p_batt_forecast')|float(0)|abs/410)|round(0,'ceil'),37]|sort)[0]
                }}
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: Grid charge
            target:
              entity_id: input_text.batt_mode
        alias: Grid charge
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            above: -1
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            below: 1
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            data:
              value: "100"
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: 37
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: Idle
            target:
              entity_id: input_text.batt_mode
        alias: Idle
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            above: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            above: 1
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            data:
              value: "13"
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_power
                - number.inverter_prog2_power
                - number.inverter_prog3_power
                - number.inverter_prog4_power
                - number.inverter_prog5_power
                - number.inverter_prog6_power
            data:
              value: "{{ states('sensor.p_batt_forecast')|float(0)|abs }}"
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: 37
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: Limited use
            target:
              entity_id: input_text.batt_mode
        alias: Limited use
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            above: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            below: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            above: -1
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            data:
              value: "13"
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_power
                - number.inverter_prog2_power
                - number.inverter_prog3_power
                - number.inverter_prog4_power
                - number.inverter_prog5_power
                - number.inverter_prog6_power
            data:
              value: 20000
          - service: number.set_value
            target:
              entity_id: number.inverter_battery_max_charge_current
            data:
              value: 37
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Enable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Zero Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: Max use
            target:
              entity_id: input_text.batt_mode
        alias: Max use
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            above: 1
          - condition: numeric_state
            entity_id: sensor.p_grid_forecast
            below: -1
          - condition: numeric_state
            entity_id: sensor.unit_prod_price
            above: 0
        sequence:
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_prog1_charge
                - select.inverter_prog2_charge
                - select.inverter_prog3_charge
                - select.inverter_prog4_charge
                - select.inverter_prog5_charge
                - select.inverter_prog6_charge
            data:
              option: No Grid or Gen
          - service: number.set_value
            data:
              value: "13"
            target:
              entity_id:
                - number.inverter_prog1_capacity
                - number.inverter_prog2_capacity
                - number.inverter_prog3_capacity
                - number.inverter_prog4_capacity
                - number.inverter_prog5_capacity
                - number.inverter_prog6_capacity
          - service: number.set_value
            target:
              entity_id:
                - number.inverter_prog1_power
                - number.inverter_prog2_power
                - number.inverter_prog3_power
                - number.inverter_prog4_power
                - number.inverter_prog5_power
                - number.inverter_prog6_power
            data:
              value: "{{ states('sensor.p_batt_forecast')|float(0)|abs}}"
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_grid_peak_shaving
            data:
              option: Disable
          - service: select.select_option
            target:
              entity_id:
                - select.inverter_load_limit
            data:
              option: Allow Export
          - service: input_text.set_value
            metadata: {}
            data:
              value: Battery sell
            target:
              entity_id: input_text.batt_mode
        alias: Battery sell
mode: restart
